### ISSUE TITLE
Why are all the tools commented out in the dockerfile? 

### ISSUE THREAD

**Issue by alexlenail** [bgruening/docker-galaxyp#3]
https://github.com/bgruening/docker-galaxyp/blob/master/Dockerfile#L25-L62

**Comment by bgruening** [comment]
Compile time. We are in a process of migrating everything over to conda packages and this will reduce compile time of such a large image so we can activate it all tools and test them with travis soon.
@zfrenchee we need help with this so if you want to make this happen earlier shim in :)

**Comment by alexlenail** [comment]
So if you wanted to build this image, you would uncomment all of it?

**Comment by bgruening** [comment]
You can build it locally not problem, but not automatically with travis or Dockerhub, they have a build-time out.
